---
title: "Homework 11-19"
output: html_document
---
```{r}
test=matrix(c(23,27,7,3),ncol = 2)

chisq.test(test)

```
认为并没有优于

```{r (a)}
test=matrix(c(10,14,11,49),ncol = 2)
fisher.test(test,alternative = "greater")

```
p<0.05，拒绝原假设，认为男性的聘用比例大于女性
```{r}
institute=c(rep("Edu",4),rep("Man",4),rep("Con",4))
sex=rep(c("M","M","F","F"),3)
hire=rep(c("Hire","Reject"),6)
num=c(2,8,12,48,5,0,1,0,3,3,1,1)
data=data.frame(institute,sex,hire,num)
data2=xtabs(num~sex+hire+institute,data)

mantelhaen.test(data2,alternative = "less")
```
p=0.5可见无法拒绝原假设，认为没有对男女录取比的偏见，这种差异的原因在于学院对于录取比的强相关使得教育学院大量的女性报名者在分析中占据了重要地位


```{r}
score=matrix(c(9,14,11,6),ncol = 2)
fisher.test(score)
chisq.test(score)
```
接受原假设，认为美国公民和非美国公民比例一样。

```{r}
test=matrix(c(4,0,4,4),ncol = 2)

# mcnemar.test(test)
binom.test(4,4,0.5)#n=b+c

```

p值为0.125，接受原假设，认为对技巧1和技巧2没有偏见

```{r 1}

library(ggplot2)
data=read.csv("C:/Users/yecha/Downloads/Epidemic.csv")
str(data)
data$Disease=factor(data$Disease)
data$Sector=factor(data$Sector)
for (i in 1:98) {

  if (data[i,"SS1"]==0 ) {
    if (data[i,"SS2"]==0 ) {
      data$level[i]="h"}
      else
       {data$level[i]="l"}
  }
    else 
      {data$level[i]="m"}
  
}

data2=xtabs(~Disease+level,data)
data2
chisq.test(data2)
#经济水平对患病无关

data2=xtabs(~Disease+Sector,data)
data2
chisq.test(data2)
#地区对患病强相关
for (i in 1:98) {
  if (data[i,"Age"]>=30) {
    data$agelevel[i]="old"
  }
    else
    {data$agelevel[i]="young"}
  
}
agelevel2=ifelse(data$Age<20,"very young",
             ifelse(data$Age<=40,"young",
                    ifelse(data$Age<=60,"middle age",
                                  ifelse(data$Age<=150,"old","not human"))))
data=cbind(data,agelevel2)

ggplot(data,aes(x=agelevel2))+geom_bar(aes(fill=Disease),position = "fill")

data2=xtabs(~Disease+agelevel2,data)
data2
chisq.test(data2)

data2=xtabs(~Disease+level+Sector,data)
data2
mantelhaen.test(data2)

data2=xtabs(~Disease+agelevel2+Sector,data)
data2
mantelhaen.test(data2)

```







