---
title: "note 11-18"
output: pdf_document
---

```{r 1}

library(ggplot2)
data=read.csv("C:/Users/yecha/Downloads/Epidemic.csv")
str(data)
data$Disease=factor(data$Disease)
data$Sector=factor(data$Sector)
for (i in 1:98) {

  if (data[i,"SS1"]==0 ) {
    if (data[i,"SS2"]==0 ) {
      data$level[i]="h"}
      else
       {data$level[i]="l"}
  }
    else 
      {data$level[i]="m"}
  
}

data2=xtabs(~Disease+level,data)
data2
chisq.test(data2)
#经济水平对患病无关

data2=xtabs(~Disease+Sector,data)
data2
chisq.test(data2)
#地区对患病强相关
for (i in 1:98) {
  if (data[i,"Age"]>=30) {
    data$agelevel[i]="old"
  }
    else
    {data$agelevel[i]="young"}
  
}
agelevel2=ifelse(data$Age<20,"very young",
             ifelse(data$Age<=40,"young",
                    ifelse(data$Age<=60,"middle age",
                                  ifelse(data$Age<=150,"old","not human"))))
data=cbind(data,agelevel2)

ggplot(data,aes(x=agelevel2))+geom_bar(aes(fill=Disease),position = "fill")

data2=xtabs(~Disease+agelevel2,data)
data2
chisq.test(data2)

data2=xtabs(~Disease+level+Sector,data)
data2
mantelhaen.test(data2)
```



```{r}
B=read.table("C:/Users/yecha/Downloads/bonus.txt",header = T)
#在方差分析之前要进行正态性检验
B
data=stack(B)
data=B
shapiro.test(data$X1)
ks.test(data$X1,"pnorm",mean(data$X1),sd(data$X1))
par(mfrow =c( 2 , 2 ) , mar = c ( 2 , 2.5 , 3 , 2 ) )
qqnorm(data$X1,main="Norm Q-Q plot of X1"); qqline(data$X1,col="red")


Y=c(data$X1,data$X2,data$X3,data$X4)
D=data.frame(Y,A=gl(4,9,36)) #gl函数用来生成factor变量，第一个参数n表示level数，第二个参数表示重复几次，第三个参数表示生成的长度
bartlett.test(Y~A,data=D)#进行方差齐性检验：方差分析的前提首先是各个因素下服从正态分布，其次服从的正态分布的方差要相同，然后通过方差来对各个水平下的均值进行假设检验


library(car)
leveneTest(Y~A,data=D)
ml=aov(Y~A,data=D)
ml
T=read.csv("C:/Users/yecha/Downloads/Timber.csv",header=T)
TS=na.omit(stack(T))

ml=aov(values~ind,data=TS)

TukeyHSD(ml)

pairwise.t.test(D$Y,D$A,"none")
B=read.csv("C:/Users/yecha/Downloads/bonus2.csv",header=T)
plot(B$Level[B$Age==1],B$Y[B$Age==1],ylim=c(min(B$Y),max(B$Y)),pch=15,xlab="奖
金水平",ylab="再就业时间")
points(B$Level[B$Age==2],B$Y[B$Age==2],pch=5)
points(B$Level[B$Age==3],B$Y[B$Age==3],pch=21)
legend(3.3,105,c("Age 1","Age 2","Age 3"),pch=c(15,5,21))
with(B,{interaction.plot(Level,Age,Y)}) #¿interaction.plot(B$Level,B$Age,B$Y) ,with用于把变量直接添加到环境，例如with(data,cbind(a1,a2))
with(B,{interaction.plot(Age,Level,Y)})
```

```{r}
data=read.table("C:/Users/yecha/Downloads/deathpenalty.txt",header = T)

data.glm=glm(cbind(DeathY,DeathN)~Aggrav+Race,family = binomial("logit"),data=data)

cbind(data$DeathY,data$DeathN)


data.glm
summary(data.glm)
anova(data.glm,Test="Chisq")


data.glm=glm(cbind(DeathY,DeathN)~Race+Aggrav,family = binomial("logit"),data=data)
summary(data.glm)

anova(data.glm,Test="Chisq")

plot(data.glm$fitted.values[data$Race=="White"],type="b",pch=19)
points(data.glm$fitted.values[data$Race=="Black"],type="b",pch=24)
legend(1,1,0,c("White","Black"),pch=c(19,24))

data.glm$fitted.values
```


```{r}
#####Chapter Logistic regression#######
library(ROCR)
library(ggplot2)

#####Example1: Death Penalty#######
###汇总数据结构############
DP<-read.table("C:/Users/yecha/Downloads/deathpenalty.txt",header = TRUE)
DP
##1)建立拟合方程，做方差分析
DP.form="cbind(DeathY,DeathN)~Aggrav+Race"
DPglm.out = glm(DP.form, family=binomial(logit), data=DP)
summary(DPglm.out)
pre=predict(DPglm.out,type='response')
##2）背叛死刑的概率拟合值图
plot(DPglm.out$fitted[DP$Race=="White"],type="b",pch=19,xlab="Aggravation",ylab="Probability of death sentence")
points(DPglm.out$fitted[DP$Race=="Black"],type="b",pch=24)
legend(1,1.0,c("White","Black"),pch=c(19,24))
###4)ROC曲线
data=data.frame(prob=pre,DeathY=DP$DeathY,DeathN=DP$DeathN)
data=data[order(data$prob),]
n=nrow(data)
tpr=fpr=rep(0,n)
for (i in 1:n){
  threshold=data$prob[i]
  tp=sum(data$DeathY[data$prob>=threshold])
  fp=sum(data$DeathN[data$prob>=threshold])
  tpr[i]=tp/sum(data$DeathY)  #真正率
  fpr[i]=fp/sum(data$DeathN)   #假正率
}
fpr
tpr
plot(c(1,fpr,0),c(1,tpr,0),type='l',xlim=c(0,1),ylim = c(0,1),xlab="FPR",ylab="TPR")
abline(a=0,b=1)
```


```{r}
#####Example1: Death Penalty#######
###个案数据结构############
dpen <- read.csv("C:/Users/yecha/Downloads/deathpenaltyind.csv",header = TRUE)
head(dpen)
tail(dpen)
##1)建立拟合方程，做方差分析
m1=glm(Death~VRace+Agg,family=binomial(logit),data=dpen)
m1
summary(m1)
anova(m1,test="Chisq")
##2)统计推断
## calculating logits
exp(m1$coef[2])
exp(m1$coef[3])
##3）背叛死刑的概率拟合值图
## plotting probability of getting death penalty as a function of aggravation
## separately for black (in black) and white (in red) victim
plot(dpen$Agg[dpen$VRace==1],m1$fitted[dpen$VRace==1],type="b",pch=19,xlab="Aggravation",ylab="Probability of death sentence")
points(dpen$Agg[dpen$VRace==0],m1$fitted[dpen$VRace==0],type="b",pch=24)
legend(1,1.0,c("White","Black"),pch=c(19,24))
###4)ROC曲线
pred <- prediction( m1$fitted, dpen$Death )
perf <- performance( pred, "tpr", "fpr" )
plot( perf)
abline(0,1)

##用“pROC”画ROC曲线并确定最优阈值####
library(pROC)

pre=predict(m1,type='response')
summary(pre)
DP.roc <- roc(dpen$Death,pre)
plot(DP.roc, print.auc=TRUE, auc.polygon=TRUE, grid=c(0.1, 0.2),
     grid.col=c("green", "red"), max.auc.polygon=TRUE,
     auc.polygon.col="skyblue", print.thres=TRUE)


p=pre>0.259 #生成一个逻辑数列，满足条件则为T，否则为F
x=data.frame(p,dpen$Death)
mytable=xtabs(~x$p+x$dpen.Death)

```


```{r}
#####Example2: Donner party#######
Donner<-read.table("C:/Users/yecha/Downloads/donner.txt",header = TRUE)

##（1）性别与是否活下来的列联表
xtabs(~Gender+Surv,data=Donner)

attach(Donner)
##（2）直方图
par(mfrow=c(2,1))
hist(Age[Surv==0],breaks = seq(10,70,10),freq=FALSE,main="死亡组年龄直方图",xlab = "年龄")
lines(density(Age[Surv==0]))
hist(Age[Surv==1],breaks = seq(10,70,10),freq=FALSE,main="生存组年龄直方图",xlab = "年龄")
lines(density(Age[Surv==1]))
##(3)拟合方程
DFM.out = glm(Surv~Gender*Age, family=binomial(logit),data = Donner)# *表示交互作用
summary(DFM.out)
anova(DFM.out)
DRM.out = glm(Surv~Gender+Age, family=binomial(logit),data=Donner)
summary(DRM.out)
anova(DRM.out)
##3）生存的概率拟合值图
## plotting probability of survive as a function of age
## separately for female and male
Agenew=seq(range(Age)[1]-1,range(Age)[2]+1,1)#range给出参数的最小值，最大值，用[1][2]分别表示
newdata=matrix(cbind(Agenew,Agenew,rep(0,length(Agenew)),rep(1,length(Agenew))),ncol=2)
newdata=data.frame(Age=newdata[,1],Gender=newdata[,2])
#newdata结构为每个年龄都有一男一女即，每个年龄都有0 1 两个数据
pre=predict(DRM.out,newdata,type = "response") #通过DRM.out来用gender+age对应的存活与否0/1来预测newdata存活的概率
#predict函数第一个参数为继承自glm的类，第二个参数为newdata即应用预测模型的新数据，需要有预测模型中需要的变量，type默认为c("link", "response", "terms")，对于二项分布type = "response"可以给出预测的概率值
pre
predata=data.frame(Age=newdata[,1],Gender=newdata[,2],pre=pre)#把预测结果(存活概率)和newdata组合在一起
plot(predata$Age[predata$Gender==1],predata$pre[predata$Gender==1],type="l",lty=2,xlim=c(14,66),ylim=c(0,0.9),xlab="Age",ylab="Probability of Survival") #男性的年龄和死亡率的关系，前两个参数分别是x,y,lty是linetype
points(predata$Age[predata$Gender==0],predata$pre[predata$Gender==0],type="l",lty=6)
legend(55,0.85,c("Female","Male"),lty=c(2,24))#图例前面两个参数为图例的xy位置，对应的是坐标轴上的位置

##用“pROC”画ROC曲线并确定最优阈值####
library(pROC)
DFM.pre=predict(DFM.out,type='response') 

DFM.roc <- roc(Surv,DFM.pre)
plot(DFM.roc, print.auc=TRUE, auc.polygon=TRUE, grid=c(0.1, 0.2),
     grid.col=c("green", "red"), max.auc.polygon=TRUE,
     auc.polygon.col="skyblue", print.thres=TRUE)

DRM.pre=predict(DRM.out,type='response')
DRM.roc <- roc(Surv,DRM.pre)
plot(smooth(DRM.roc), print.auc=TRUE, auc.polygon=TRUE, grid=c(0.1, 0.2),
     grid.col=c("green", "red"), max.auc.polygon=TRUE,
     auc.polygon.col="skyblue", print.thres=TRUE)
```


```{r}
#### ******* German Credit Data ******* ####
#### ******* data on 1000 loans ******* ####


## read data and create relevant variables
credit <- read.csv("C:/Users/yecha/Downloads/germancredit.csv");
str(credit)

credit$Default <- factor(credit$Default);

###重新定义某些变量的分类###########
credit$history = factor(credit$history, levels=c("A30","A31","A32","A33","A34"));
levels(credit$history) = c("good","good","poor","poor","terrible");
credit$foreign <- factor(credit$foreign, levels=c("A201","A202"), labels=c("foreign","german"));
credit$rent <- factor(credit$housing=="A151");
credit$purpose <- factor(credit$purpose, levels=c("A40","A41","A42","A43",
                                                  "A44","A45","A46","A47","A48","A49","A410"));
levels(credit$purpose) <- c("newcar","usedcar",rep("goods/repair",4),"edu",NA,"edu","biz","biz");

## for demonstration, cut the dataset to these variables
credit <- credit[,c("Default","duration","amount","installment","age", "history", 
                    "purpose","foreign","rent")]


str(credit)
library(dplyr)
model<-glm(Default~duration+amount+installment+age+history+purpose+foreign+rent,family = binomial("logit"),data=credit) 
model<-glm(Default~.,family = binomial("logit"),data=credit) #用.表示其他一切变量
model%>%
anova()
model %>%
  summary()

Default=credit$Default
pre=model %>% 
  predict(type="response")%>%
roc(Default,.) %>%
plot( print.auc=TRUE, auc.polygon=TRUE, grid=c(0.1, 0.2),
     grid.col=c("green", "red"), max.auc.polygon=TRUE,
     auc.polygon.col="skyblue", print.thres=TRUE)
```

